export const PROMPT_TYPES = Object.freeze({
    SUMMARY_V2: 'SUMMARY_V2',
    MONOLOG: 'MONOLOG',
    NEXT_STEPS: 'NEXT_STEPS',
    CADENCE_FAST: 'CADENCE_FAST',
    SEQUENCE: 'SEQUENCE',
    OBJECTION_RESPONSE: 'OBJECTION_RESPONSE',
    TRIGGER: 'TRIGGER',
    BUYING_INTENT: 'BUYING_INTENT'
})

export const BEHAVIORAL_PROMPTS = [PROMPT_TYPES.MONOLOG, PROMPT_TYPES.NEXT_STEPS, PROMPT_TYPES.CADENCE_FAST]

export const BEHAVIORAL_PROMPTS_TO_IMAGE = Object.freeze({
    [PROMPT_TYPES.MONOLOG]: '/images/monologue.png',
    [PROMPT_TYPES.CADENCE_FAST]: '/images/slow_down.png'
})

export const PROMPTS_TO_ONLY_DEMO_MODE = Object.freeze({
    SUMMARY: false,
    MONOLOG: false,
    NEXT_STEPS: false,
    CADENCE_FAST: false,
    SEQUENCE: true,
    OBJECTION_RESPONSE: false,
    BUYING_INTENT: false
})
